### ISSUE TITLE
change from HDB (berkeley) to MDB (LMDB) backend

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#17]
Info about the MDB backend from the OpenLDAP documentation (https://www.openldap.org/doc/admin24/backends.html):

The mdb backend to slapd(8) is the recommended primary backend for a normal slapd database. It uses OpenLDAP's own Lightning Memory-Mapped Database (LMDB) library to store data and is intended to replace the Berkeley DB backends. It supports indexing like the BDB backends, but it uses no caching and requires no tuning to deliver maximum search performance. Like hdb, it is also fully hierarchical and supports subtree renames in constant time.

On 07/20/2018 01:15 PM, Robert McDermott wrote:
I think I found the problem (or at least a way to dramatically speed things up).  All of our LDAP servers are using the older much slower HDB database backend, rather than the recommended MDB (memory mapped DB).
Here how to check which backend database is in use:
Gizmo2:
$ sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=module{0},cn=config" |grep back
olcModuleLoad: {0}back_hdb
ldap-j4-01-prd:
$ sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=module{0},cn=config" |grep back
olcModuleLoad: {0}back_hdb
ldap-j4-02-prd:
$ sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=module{0},cn=config" |grep back
olcModuleLoad: {0}back_hdb

Here is what it looks like on a test ladp server with a fresh install (apt install slapd):

ldaptest.fhcrc.org:
sudo ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=module{0},cn=config"|grep back
olcModuleLoad: {0}back_mdb

So "MDB" is the default.  We are overriding the default somewhere during the configuration phase and selecting the older/slower database. It looks like we are configuring to use the old database in this file:
https://github.com/FredHutch/ad2openldap/blob/master/ldif/ad2openldap_config_rfc2307bis.ldif#L636 which is used to configure our ldap servers.

**Comment by jmkatcher** [comment]
I'm reluctant to submit this as it requires a reinstall from scratch

**Comment by dirkpetersen** [comment]
I was wondering if there was an easy way to make this conditional?  New installs use LMDB and for existing ones it just leaves in place what it finds. ?

**Comment by jmkatcher** [comment]
I'm not convinced there's anyway to make this easy.  Really the thing to is to strip out the effectively unused rfc2307bis include (which defines the hdb stuff - I didn't include this for the record) and let things happily default.  The problem is how to do any of this without breaking existing installs when Chef mindlessly copies a new config in place.

**Comment by jmkatcher** [comment]
Now installed and in production - .ldif.mdb is the correct one for an mdb configuration
