### ISSUE TITLE
where do the 2 ldif files go 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#2]
the 2 ldif files also need to be part of the package . If they go directly in /etc/ad2openldap/ldif the package can only be installed as root. it then needs to fail somehow gracefully if an attempt is made to install it as user.

**Comment by jmkatcher** [comment]
I'm _extremely_ unclear about this installation process.  Both how to specify the mandated presence of external files like the 2 ldif files and the startup process for something that's not really a Python package per se.

**Comment by dirkpetersen** [comment]
this is how I got the old one going on 16.04, those ldifs are in the deb file

apt-get install slapd python-yaml
apt-get install python-pip python-dev libldap2-dev libsasl2-dev libssl-dev
pip install python-ldap==2.3.13
wget https://github.com/FredHutch/IT/raw/master/general/ad2openldap/release/0.10-3/ad2openldap_0.10-3_all.deb
dpkg --force-all -i ad2openldap_0.10-3_all.deb
scp gizmo2:/etc/ad2openldap/ad2openldap.conf /etc/ad2openldap/
chgrp openldap /etc/ad2openldap/ad2openldap.conf
ad2openldap setup
ad2openldap rtcclean --dont-blame-ad2openldap -v
ad2openldap fullsync --dont-blame-ad2openldap -v
ad2openldap deltasync --dont-blame-ad2openldap -v

**Comment by dirkpetersen** [comment]
fixed
