### ISSUE TITLE
lockfile remover after timeout 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#24]
instances running are sometimes keeping their lockfiles in place.  It looks like their connections to AD just hang for some reason so I killed them manually after ~45 minutes elapsed - which automatically reaped the lock files..

It would be easy enough to add functionality that if the lockfile is checked and the running instance is older than N minutes, it would be killed and the lockfile reaped/reset as a new instance runs in its place.

**Comment by jmkatcher** [comment]
Now checked in/pulled
