### ISSUE TITLE
logging errors and connections to syslog

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#26]
ad2openldap does currently use its own logfile which does not log to splunk, we would like to

- add error logging to syslog
- catch known errors such as 
ldap3.core.exceptions.LDAPOtherResult: LDAPOtherResult - 80 - other - None - 00000008: SysErr: DSID-030222A0, problem 12 (Not enough space), data 0 
  and write a reasonable error message to syslog such as "Domain controller xyz does not have enough memory"
- track and log which domain controller it is talking to, perhaps by 

https://stackoverflow.com/questions/3993731/how-do-i-access-netstat-data-in-python 

>>> import psutil
>>> p=psutil.Process()
>>> p.name()
'python'
>>> p.connections()
[]

**Comment by jmkatcher** [comment]
Added syslog handler to logging and submitted pull

**Comment by jmkatcher** [comment]
Added logging of connected server as info

**Comment by jmkatcher** [comment]
Added exception handler for LDAPOperationResult which should at least intercept the "out of memory" class of faults and report them to syslog before crashing out.
