### ISSUE TITLE
Error while running rtcclean command

### ISSUE THREAD

**Issue by suchipa** [FredHutch/ad2openldap#3]
Command `ad2openldap3 rtcclean --dont-blame-ad2openldap -v` executed with error. Am I missing anything?

Output snippet-

```
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-11-28 20:53:48
INFO:ad2openldap3:line 206:ad2openldap - finished execution at 2017-11-28 20:54:08
Traceback (most recent call last):
  File "/usr/local/bin/ad2openldap3", line 185, in main
    rtc_substituted = rtc_template.safe_substitute(ssha=generate_ssha(config['bind_dn_password']))
  File "/usr/local/bin/ad2openldap3", line 568, in generate_ssha
    return base64.b64encode(hashlib.sha1(password + salt).digest() + salt)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by jmkatcher** [comment]
Honestly I have no idea what 'rtcclean' even does as it wasn't part of the original functionality.

I'll start looking into it on 'vagrant' assuming I have access.

**Comment by jmkatcher** [comment]
This is now fixed to the best of my ability to test it.

**Comment by suchipa** [comment]
I get another error while running `rtclean` command -

Note: vagrant is my local vm, where I am running these commands.

```
root@vagrant:/usr/local/bin# ad2openldap3 rtcclean --dont-blame-ad2openldap -v
INFO:ad2openldap3:line 54:ad2openldap - starting execution at 2017-11-30 17:50:10
INFO:ad2openldap3:line 560:Successfully executed command: iptables -A INPUT -i eth0 -p tcp --dport 389 -j REJECT
INFO:ad2openldap3:line 560:Successfully executed command: /etc/init.d/slapd stop
INFO:ad2openldap3:line 555:A problem (1) has occurred calling slapadd -F /etc/ldap/slapd.d -b cn=config -q -l /tmp/rtc.ldif
INFO:ad2openldap3:line 206:ad2openldap - finished execution at 2017-11-30 17:50:10
Traceback (most recent call last):
  File "/usr/local/bin/ad2openldap3", line 1125, in <module>
    sys.exit(main())
  File "/usr/local/bin/ad2openldap3", line 191, in main
    run_command(slapadd_rtc_ldif, verbose=arguments.verbose)
  File "/usr/local/bin/ad2openldap3", line 558, in run_command
    (return_code,command))
OSError: A problem (1) has occurred calling slapadd -F /etc/ldap/slapd.d -b cn=config -q -l /tmp/rtc.ldif
root@vagrant:/usr/local/bin# slapadd -F /etc/ldap/slapd.d -b cn=config -q -l /tmp/rtc.ldif
5a2044fd PROXIED attributeDescription "DC" inserted.
5a2044fd <= str2entry: str2ad(dc): attribute type undefined
slapadd: could not parse entry (line=1)
_###                   15.47% eta   none elapsed            none spd 222.5 k/s
Closing DB...
```

**Comment by jmkatcher** [comment]
At this point, the new version (ad2openldap3) is generating precisely the same ldif (the template file with the substituted password) as the older version.  I’m suspecting there’s something wrong with the initial configuration of openldap itself before this file is imported.

I’ll look further into this in my environment.  Could you either let me log into ‘vagrant’ or send me the /tmp/rtc.ldif file?

**Comment by suchipa** [comment]
Let me destroy the VM and re-create and test this.

**Comment by jmkatcher** [comment]
I just ran this in my environment and compared the source and result .ldif file - they're exactly the same other than the substituted password.

OpenLDAP is pretty delicate especially when constantly directly messing with its underlying database.

**Comment by jmkatcher** [comment]
Potentially interesting difference - the older one has a terminal 'newline'.  That shouldn't make a difference but I'll add if you still are seeing a problem.

**Comment by suchipa** [comment]
Thanks for fixing the issue. I am able to execute the `rtclean` command without error. The previous issue, was because of the old file I guess.
