### ISSUE TITLE
memberNisNetgroup is also required. 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#44]
https://github.com/FredHutch/ad2openldap/blob/73aad0aba35b6be5dd7956e8558c7e44ea7a98b3/ad2openldap/ad2openldap3#L1067

in addition to nisNetgroupTriple we also need to replicate attribute memberNisNetgroup

**Comment by jmkatcher** [comment]
Does 'memberNisNetgroup' accompany 'nisNetgroupTriple'? E.g. does it follow identical output rules?

**Comment by jmkatcher** [comment]
This code has now been tested and submitted.
