### ISSUE TITLE
objectType addition or removal causes error message 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#46]
adding and removing nisMaps causes this issue. 

> >  File "/usr/local/bin/ad2openldap3", line 1112, in ldif_diff
> >    raise ValueError('Number of OUs is different.  old: %s, new: %s' %
> > (old_ldif.keys(), new_ldif.keys() ))
> >
> > ValueError: Number of OUs is different.  old: dict_keys(['autofs',
> > 'netgroup', 'people', 'group']), new: dict_keys(['netgroup', 'group',
> > 'people'])

**Comment by jmkatcher** [comment]
When OU mismatch is detected, ad2openldap3 will auto revert to fullsync from deltasync.
