### ISSUE TITLE
check for existence of 'iptables' binary before launching a full sync 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#48]
>>  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
>>    raise child_exception_type(errno_num, err_msg)
>> 
>> FileNotFoundError: [Errno 2] No such file or directory: 'iptables'

**Comment by dirkpetersen** [comment]
perhaps with https://www.geeksforgeeks.org/python-shutil-which-method/

**Comment by dirkpetersen** [comment]
in chef we should make a change in the config and just use the full path of iptables, e.g. /sbin/iptables

grep iptables /etc/ad2openldap/ad2openldap.conf 
# iptables commands to add an remove rules.  If not in $PATH, specify full path.
iptables_add: /sbin/iptables -A INPUT -i $interface -p tcp --dport 389 -j REJECT
iptables_delete: /sbin/iptables -D INPUT -i $interface -p tcp --dport 389 -j REJECT

**Comment by jmkatcher** [comment]
Submitted pull request and sacrificed black goat to Chef.

**Comment by dirkpetersen** [comment]
also added pull request to chef recipe https://github.com/FredHutch/ldap_cache/pull/7/commits/a7c20afeec4287fff4759b85b5e3c5aa9a4f5326

**Comment by jmkatcher** [comment]
Is this considered resolved via explicit iptables path specification in config/template?  The program actually knows nothing of ipconfig itself, merely passing a config parameter in toto to the run_command function.

**Comment by dirkpetersen** [comment]
after further discussion this is considered resolved as the script bails out safely if iptables is not found
