### ISSUE TITLE
adding autofs maps to AD causes a full resync in  openldap

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/ad2openldap#51]
When I try to apply this ldif file on sphinx to AD ad2openldap seems to attempt a full re-sync . This should be tested. 

/tmp/ldif-map.WDO

/usr/bin/ldapadd -x -h servername -D "CN=scicomp,OU=xxxxx" -w "XXXXXXXX" -f /tmp/ldif-map.WDO

**Comment by jmkatcher** [comment]
Is this actually an error state? If added autofs maps to AD alters the number of OUs, then a full resync is the proper, programmed result.

**Comment by dirkpetersen** [comment]
OK got it
